// 静态路由表负责定义后台菜单结构、权限和页面组件映射。
export const staticRoutes: AppRoute.RowRoute[] = [
  {
    name: 'home',
    path: '/home',
    title: '首页',
    requiresAuth: true,
    icon: 'icon-park-outline:home',
    menuType: 'page',
    pinTab: true,
    componentPath: '/home/index.vue',
    id: 100,
    pid: null,
  },
  {
    name: 'analysis',
    path: '/analysis',
    title: 'AI 分析与调度',
    requiresAuth: true,
    icon: 'icon-park-outline:analysis',
    menuType: 'dir',
    componentPath: null,
    id: 101,
    pid: null,
  },
  {
    name: 'analysisCenter',
    path: '/analysis/center',
    title: '分析中心',
    requiresAuth: true,
    icon: 'icon-park-outline:analysis',
    menuType: 'page',
    pinTab: true,
    componentPath: '/analysis/center/index.vue',
    id: 102,
    pid: 101,
  },
  {
    name: 'analysisScheduler',
    path: '/analysis/scheduler',
    title: '调度中心',
    requiresAuth: true,
    icon: 'icon-park-outline:time',
    menuType: 'page',
    componentPath: '/analysis/scheduler/index.vue',
    id: 103,
    pid: 101,
  },
  {
    name: 'analysisAgentChat',
    path: '/analysis/agent-chat',
    title: 'Agent问股',
    requiresAuth: true,
    keepAlive: true,
    icon: 'icon-park-outline:message-one',
    menuType: 'page',
    componentPath: '/analysis/agent-chat/index.vue',
    id: 104,
    pid: 101,
  },
  {
    name: 'marketCenter',
    path: '/market/center',
    title: '行情与策略展示',
    requiresAuth: true,
    keepAlive: true,
    icon: 'icon-park-outline:chart-line',
    menuType: 'page',
    componentPath: '/market/center/index.vue',
    id: 201,
    pid: null,
  },
  {
    name: 'backtestCenter',
    path: '/backtest/center',
    title: '回测与统计',
    requiresAuth: true,
    keepAlive: true,
    icon: 'icon-park-outline:file-code',
    menuType: 'page',
    componentPath: '/backtest/center/index.vue',
    id: 301,
    pid: null,
  },
  {
    name: 'systemConfig',
    path: '/system/config',
    title: '配置管理',
    requiresAuth: true,
    roles: ['admin'],
    icon: 'icon-park-outline:config',
    menuType: 'page',
    componentPath: '/system/config/index.vue',
    id: 401,
    pid: 5,
  },
  {
    name: 'profileSettings',
    path: '/profile/settings',
    title: '个人配置',
    requiresAuth: true,
    icon: 'icon-park-outline:personal-privacy',
    menuType: 'page',
    componentPath: '/profile/settings/index.vue',
    id: 601,
    pid: null,
  },
  {
    name: 'profileTrading',
    path: '/profile/trading',
    title: '交易账户中心',
    requiresAuth: true,
    icon: 'icon-park-outline:stock-market',
    menuType: 'page',
    componentPath: '/profile/trading/index.vue',
    id: 602,
    pid: null,
  },
  {
    name: 'admin',
    path: '/admin',
    title: '后台管理',
    requiresAuth: true,
    roles: ['admin'],
    icon: 'icon-park-outline:people-safe',
    menuType: 'dir',
    componentPath: null,
    id: 5,
    pid: null,
  },
  {
    name: 'adminUsers',
    path: '/admin/users',
    title: '用户管理',
    requiresAuth: true,
    roles: ['admin'],
    icon: 'icon-park-outline:every-user',
    menuType: 'page',
    componentPath: '/admin/users/index.vue',
    id: 502,
    pid: 5,
  },
  {
    name: 'adminLogs',
    path: '/admin/logs',
    title: '日志管理',
    requiresAuth: true,
    roles: ['admin'],
    icon: 'icon-park-outline:log',
    menuType: 'page',
    componentPath: '/admin/logs/index.vue',
    id: 504,
    pid: 5,
  },
]
