export const staticRoutes: AppRoute.RowRoute[] = [
  {
    name: 'analysisCenter',
    path: '/analysis/center',
    title: 'AI 分析与调度',
    requiresAuth: true,
    icon: 'icon-park-outline:analysis',
    menuType: 'page',
    pinTab: true,
    componentPath: '/analysis/center/index.vue',
    id: 101,
    pid: null,
  },
  {
    name: 'marketCenter',
    path: '/market/center',
    title: '行情与策略展示',
    requiresAuth: true,
    icon: 'icon-park-outline:chart-line',
    menuType: 'page',
    componentPath: '/market/center/index.vue',
    id: 201,
    pid: null,
  },
  {
    name: 'backtestCenter',
    path: '/backtest/center',
    title: '回测与统计',
    requiresAuth: true,
    icon: 'icon-park-outline:file-code',
    menuType: 'page',
    componentPath: '/backtest/center/index.vue',
    id: 301,
    pid: null,
  },
  {
    name: 'systemConfig',
    path: '/system/config',
    title: '配置管理',
    requiresAuth: true,
    roles: ['super_admin'],
    icon: 'icon-park-outline:config',
    menuType: 'page',
    componentPath: '/system/config/index.vue',
    id: 401,
    pid: null,
  },
  {
    name: 'profileSettings',
    path: '/profile/settings',
    title: '个人配置',
    requiresAuth: true,
    icon: 'icon-park-outline:personal-privacy',
    menuType: 'page',
    componentPath: '/profile/settings/index.vue',
    id: 601,
    pid: null,
  },
  {
    name: 'profileTrading',
    path: '/profile/trading',
    title: '交易账户中心',
    requiresAuth: true,
    icon: 'icon-park-outline:stock-market',
    menuType: 'page',
    componentPath: '/profile/trading/index.vue',
    id: 602,
    pid: null,
  },
  {
    name: 'admin',
    path: '/admin',
    title: '后台管理',
    requiresAuth: true,
    roles: ['super_admin'],
    icon: 'icon-park-outline:people-safe',
    menuType: 'dir',
    componentPath: null,
    id: 5,
    pid: null,
  },
  {
    name: 'adminStrategy',
    path: '/admin/strategy',
    title: '策略参数',
    requiresAuth: true,
    roles: ['super_admin'],
    icon: 'icon-park-outline:tuning',
    menuType: 'page',
    componentPath: '/admin/strategy/index.vue',
    id: 501,
    pid: 5,
  },
  {
    name: 'adminUsers',
    path: '/admin/users',
    title: '用户管理',
    requiresAuth: true,
    roles: ['super_admin'],
    icon: 'icon-park-outline:every-user',
    menuType: 'page',
    componentPath: '/admin/users/index.vue',
    id: 502,
    pid: 5,
  },
  {
    name: 'adminRoles',
    path: '/admin/roles',
    title: '角色管理',
    requiresAuth: true,
    roles: ['super_admin'],
    icon: 'icon-park-outline:permissions',
    menuType: 'page',
    componentPath: '/admin/roles/index.vue',
    id: 503,
    pid: 5,
  },
  {
    name: 'adminLogs',
    path: '/admin/logs',
    title: '操作日志',
    requiresAuth: true,
    roles: ['super_admin'],
    icon: 'icon-park-outline:log',
    menuType: 'page',
    componentPath: '/admin/logs/index.vue',
    id: 504,
    pid: 5,
  },
]
