// This file is generated by scripts/generate-runtime-icons.mjs.
// Do not edit manually.

export const vendoredRuntimeIconPathMap = {
  'icon-park-outline:home': '/src/assets/runtime-icons/icon-park-outline/home.svg',
  'icon-park-outline:analysis': '/src/assets/runtime-icons/icon-park-outline/analysis.svg',
  'icon-park-outline:time': '/src/assets/runtime-icons/icon-park-outline/time.svg',
  'icon-park-outline:chart-line': '/src/assets/runtime-icons/icon-park-outline/chart-line.svg',
  'icon-park-outline:file-code': '/src/assets/runtime-icons/icon-park-outline/file-code.svg',
  'icon-park-outline:config': '/src/assets/runtime-icons/icon-park-outline/config.svg',
  'icon-park-outline:personal-privacy': '/src/assets/runtime-icons/icon-park-outline/personal-privacy.svg',
  'icon-park-outline:stock-market': '/src/assets/runtime-icons/icon-park-outline/stock-market.svg',
  'icon-park-outline:people-safe': '/src/assets/runtime-icons/icon-park-outline/people-safe.svg',
  'icon-park-outline:setting-two': '/src/assets/runtime-icons/icon-park-outline/setting-two.svg',
  'icon-park-outline:every-user': '/src/assets/runtime-icons/icon-park-outline/every-user.svg',
  'icon-park-outline:log': '/src/assets/runtime-icons/icon-park-outline/log.svg',
  'icon-park-outline:ghost': '/src/assets/runtime-icons/icon-park-outline/ghost.svg',
  'icon-park-outline:user-business': '/src/assets/runtime-icons/icon-park-outline/user-business.svg',
  'icon-park-outline:setting-config': '/src/assets/runtime-icons/icon-park-outline/setting-config.svg',
  'icon-park-outline:logout': '/src/assets/runtime-icons/icon-park-outline/logout.svg',
} as const

export type VendoredRuntimeIconName = keyof typeof vendoredRuntimeIconPathMap
